---
# tasks file for wordpress
- import_tasks: add_client.yml
- import_tasks: config_webserver.yml
- import_tasks: config_client_web.yml
#- import_tasks: config_wp.yml
- import_tasks: activate_web.yml
